
import com.toedter.calendar.JDateChooser;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import org.jcp.xml.dsig.internal.SignerOutputStream;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author ZAX
 */
public class EmployeeInfo extends javax.swing.JFrame {

    /**
     * Creates new form EmployeeInfo
     */
    public EmployeeInfo() {
        initComponents();

    }

    public EmployeeInfo(String p) {
        initComponents();
        if (p.equals("add")) {
            ButtonUpdate.setVisible(false);
            ButtonShow.setVisible(false);
            searchTF.setVisible(false);
            jLabel26.setVisible(false);
            jLabel7.setVisible(false);
            LeavingDate.setVisible(false);
        } else if (p.equals("search")) {
            ButtonSave.setVisible(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        FirstNameTF = new javax.swing.JTextField();
        LastNameTF = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        MaleBT = new javax.swing.JRadioButton();
        FemaleBT = new javax.swing.JRadioButton();
        jLabel16 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        MobileOfficeTF = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        MobilePersonalTF = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        EmailTF = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        DesignationTF = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        DepartmentTF = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        VillageTF = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        P_PostOfficeTF = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        District = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        ButtonSave = new javax.swing.JButton();
        DOB = new com.toedter.calendar.JDateChooser();
        JoiningDate = new com.toedter.calendar.JDateChooser();
        LeavingDate = new com.toedter.calendar.JDateChooser();
        ButtonUpdate = new javax.swing.JButton();
        ButtonShow = new javax.swing.JButton();
        searchTF = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        PasswordTF = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        LastNameTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LastNameTFActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Employee's Information");

        jLabel2.setText("First Name *  : ");

        jLabel3.setText("Last Name * :");

        buttonGroup1.add(MaleBT);
        MaleBT.setText("Male");

        buttonGroup1.add(FemaleBT);
        FemaleBT.setText("Female");
        FemaleBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FemaleBTActionPerformed(evt);
            }
        });

        jLabel16.setText("Gender : ");

        jLabel19.setText("DateOfBirth :");

        jLabel12.setText("Mobile (Office) * : ");

        jLabel20.setText("Mobile (Personal)* :");

        EmailTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmailTFActionPerformed(evt);
            }
        });

        jLabel21.setText("Emalil * :");

        DesignationTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DesignationTFActionPerformed(evt);
            }
        });

        jLabel22.setText("Designation * : ");

        DepartmentTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DepartmentTFActionPerformed(evt);
            }
        });

        jLabel4.setText("Address * :");

        jLabel5.setText("  Village  :");

        P_PostOfficeTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                P_PostOfficeTFActionPerformed(evt);
            }
        });

        jLabel17.setText("PostOffice :");

        District.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dhaka", "Khulna", "Barishal", "Rangpur", "Gazipur", "Barguna", "Barishal", "Pirojpur", "Rangamati", "Magura", "Patuakhali", "Dinajpur", "Moulovibazar", "Khagrachori", "Jamalpur", "Mymensingh", "Joypurhat", "SreeMongol" }));
        District.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel8.setText(" District  :");

        jLabel24.setText("JoiningDate * :");

        jLabel25.setText("Department * : ");

        jLabel26.setText("LeavingDate :");

        ButtonSave.setText("Save");
        ButtonSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonSaveActionPerformed(evt);
            }
        });

        ButtonUpdate.setText("Update");
        ButtonUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonUpdateActionPerformed(evt);
            }
        });

        ButtonShow.setText("Show");
        ButtonShow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonShowActionPerformed(evt);
            }
        });

        jLabel6.setText("Password:");

        jLabel7.setText("Employees Id:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel2)
                .addGap(34, 34, 34)
                .addComponent(FirstNameTF, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ButtonSave, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ButtonUpdate)
                .addGap(199, 199, 199))
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel20)
                        .addGap(17, 17, 17)
                        .addComponent(MobilePersonalTF, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(65, 65, 65)
                        .addComponent(jLabel12)
                        .addGap(18, 18, 18)
                        .addComponent(MobileOfficeTF, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel17)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(P_PostOfficeTF, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(District, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(VillageTF, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(searchTF, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(ButtonShow))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(PasswordTF, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(LastNameTF, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap())))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(DOB, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44)
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(MaleBT)
                        .addGap(18, 18, 18)
                        .addComponent(FemaleBT)
                        .addGap(429, 429, 429))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel21)
                                .addGap(40, 40, 40)
                                .addComponent(EmailTF, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel22)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(DesignationTF, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel25)
                                .addGap(16, 16, 16)
                                .addComponent(DepartmentTF, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel26)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(LeavingDate, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(1, 1, 1)
                                        .addComponent(JoiningDate, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(643, 643, 643))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(LastNameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FirstNameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MobileOfficeTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel20)
                    .addComponent(MobilePersonalTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(DOB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(MaleBT)
                        .addComponent(FemaleBT)
                        .addComponent(jLabel16)))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel25)
                            .addComponent(DepartmentTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel22)
                            .addComponent(DesignationTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(EmailTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel21)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel24, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(PasswordTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(JoiningDate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel26)
                    .addComponent(LeavingDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(VillageTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(P_PostOfficeTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(District, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(searchTF)
                            .addComponent(jLabel7))
                        .addComponent(ButtonShow, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonSave)
                    .addComponent(ButtonUpdate))
                .addGap(32, 32, 32))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void FemaleBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FemaleBTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FemaleBTActionPerformed

    private void EmailTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmailTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EmailTFActionPerformed

    private void JoiningDateComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_JoiningDateComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_JoiningDateComponentAdded

    private void LastNameTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LastNameTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LastNameTFActionPerformed

    private void DesignationTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DesignationTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DesignationTFActionPerformed

    private void LeavingDateComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_LeavingDateComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_LeavingDateComponentAdded

    private void DepartmentTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DepartmentTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DepartmentTFActionPerformed

    private void ButtonSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonSaveActionPerformed

        try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            Connection conn = DriverManager
                    .getConnection(
                            "jdbc:sqlserver://localhost:1433;databaseName=HumanResource_payroll;selectMethod=cursor", "sa", "123456");
            String sql = "INSERT INTO employee(FirstName,LastName,MobileNoPersonal,MobileNoOffice,DOB,Gender,Email,Designation,Department,EmployeeJoiningDate,EmployeeLeavingDate,pass) values(?,?,?,?,?,?,?,?,?,?,?,?)";
            PreparedStatement pst = conn.prepareStatement(sql);
            pst.setString(1, FirstNameTF.getText());
            pst.setString(2, LastNameTF.getText());
            pst.setString(3, MobilePersonalTF.getText());
            pst.setString(4, MobileOfficeTF.getText());

            SimpleDateFormat dcn = new SimpleDateFormat("yyyy-MM-dd");
            String date = dcn.format(DOB.getDate());

            pst.setString(5, date);

            String gender = "";

            if (MaleBT.isSelected()) {
                gender = "Male";
            }
            if (FemaleBT.isSelected()) {
                gender = "Female";
            }
            pst.setString(6, gender);

            pst.setString(7, EmailTF.getText());
            pst.setString(8, DesignationTF.getText());
            pst.setString(9, DepartmentTF.getText());
            SimpleDateFormat dcn1 = new SimpleDateFormat("yyyy-MM-dd");
            String date1 = dcn1.format(JoiningDate.getDate());

            pst.setString(10, date1);
            
            String date2 = null;
            pst.setString(11, date2);
            
            pst.setString(12,PasswordTF.getText());

            pst.executeUpdate();
            
            
            String Sql4="select EmployeeId from employee where Email='"+EmailTF.getText()+"'";
            System.out.println(Sql4);
            Statement st4=conn.createStatement();
            System.out.println(st4);
            ResultSet rrss =st4.executeQuery(Sql4);
            String Ids="";
            
            
            while(rrss.next())
            {
                Ids=rrss.getString("EmployeeId");
                System.out.println(rrss.getString("EmployeeId"));
            }
            
            int EmployeeId1=Integer.parseInt(Ids);
            
            
            
         
            
            String sql1 = "insert into ADDRESS_LOCATION(EmployeeId,Village, PostOffice ,District) values(?,?,?,?)";
            PreparedStatement pst1 = conn.prepareStatement(sql1);

            pst1.setInt(1,EmployeeId1);
            pst1.setString(2, VillageTF.getText());
            pst1.setString(3, P_PostOfficeTF.getText());

            String DistrictSelectedValue = District.getSelectedItem().toString();

            pst1.setString(4, DistrictSelectedValue);

            pst1.executeUpdate();
            
            String Sql3="select EmployeeId from employee where Email='"+EmailTF.getText()+"'";
            System.out.println(Sql3);
            Statement st5=conn.createStatement();
            System.out.println(st5);
            ResultSet rrs =st5.executeQuery(Sql3);
            String Id="";
            
            
            while(rrs.next())
            {
                Id=rrs.getString("EmployeeId");
                System.out.println(rrs.getString("EmployeeId"));
            }
            
            int EmployeeId=Integer.parseInt(Id);
            
            String sql2 = "insert into user_profiles(EmployeeId, Email ,Pass) values(?,?,?)";
            PreparedStatement pst2 = conn.prepareStatement(sql2);

            pst2.setInt(1, EmployeeId);
            pst2.setString(2, EmailTF.getText());
            pst2.setString(3, PasswordTF.getText());
            pst2.executeUpdate();
            
            
            JOptionPane.showMessageDialog(null, "Inserted Successfully");
            
               String p=Id;
               String Desig=DesignationTF.getText();
       
             new Salary(p,Desig).setVisible(true);
               setVisible(false);
            
        } catch (Exception e) {

            System.out.println(e);
            JOptionPane.showMessageDialog(null, e);

        }

    }//GEN-LAST:event_ButtonSaveActionPerformed

    private void P_PostOfficeTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_P_PostOfficeTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_P_PostOfficeTFActionPerformed

    private void ButtonUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonUpdateActionPerformed
       
        try{
            
             Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            Connection conn = DriverManager
                    .getConnection(
                            "jdbc:sqlserver://localhost:1433;databaseName=HumanResource_payroll;selectMethod=cursor", "sa", "123456");
            String FirstName=FirstNameTF.getText();
            String LastName=LastNameTF.getText();
            String MobileNoPersonal=MobilePersonalTF.getText();
            String MobileNoOffice=MobileOfficeTF.getText();
            
            
             SimpleDateFormat dcn = new SimpleDateFormat("yyyy-MM-dd");
             String dateOfBirth = dcn.format(DOB.getDate());
             
            String gender = "";

            if (MaleBT.isSelected()) {
                gender = "Male";
            }
            if (FemaleBT.isSelected()) {
                gender = "Female";
            }
            String Email=EmailTF.getText();
            String Designation=DesignationTF.getText();
            String Department=DepartmentTF.getText();
            
            SimpleDateFormat dcn1 = new SimpleDateFormat("yyyy-MM-dd");
            String joiningDate = dcn1.format(JoiningDate.getDate());
            
           
            String leavingDate;
            if (LeavingDate.getDate() == null) {
                 leavingDate = null;
                
            }else {
                SimpleDateFormat dcn2 = new SimpleDateFormat("yyyy-MM-dd");

                leavingDate = dcn2.format(LeavingDate.getDate());
            }
            
            String Village =VillageTF.getText();
            String PostOffice=P_PostOfficeTF.getText();
            String DistrictSelectedValue = District.getSelectedItem().toString();
            
            String sqlupdate = "UPDATE employee SET FirstName="+"'"+FirstName+"'"+",LastName='"+LastName+"',Gender='"+gender+"',DOB='"+dateOfBirth+"',MobileNoOffice='"+MobileNoOffice+"',MobileNoPersonal='"+MobileNoPersonal+"',Email='"+Email+"',Designation='"+Designation+"',Department='"+Department+"',EmployeeJoiningDate='"+joiningDate+"',EmployeeLeavingDate='"+leavingDate+"' where EmployeeId='"+Integer.parseInt(searchTF.getText())+"'";
          System.out.println(sqlupdate);
            
            
            Statement stt= conn.createStatement();
            stt.executeUpdate(sqlupdate);
            
            
            
            
            
        
        }catch(Exception e){
        
        }
        
        
        
        
        
        
        
        
    }//GEN-LAST:event_ButtonUpdateActionPerformed

    private void ButtonShowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonShowActionPerformed
        String id = searchTF.getText().trim();
        int i = Integer.parseInt(id);
        try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            Connection conn = DriverManager
                    .getConnection(
                            "jdbc:sqlserver://localhost:1433;databaseName=HumanResource_payroll;selectMethod=cursor", "sa", "123456");

            String sql = "select employee.*,ADDRESS_LOCATION.* from employee  FULL JOIN ADDRESS_LOCATION  ON employee.EmployeeId=ADDRESS_LOCATION.EmployeeId where employee.EmployeeId='" + i + "'";
            System.out.println(sql);

            Statement smt = conn.createStatement();
            ResultSet rs = smt.executeQuery(sql);
            String sql1="select Pass from user_profiles where EmployeeId='"+id+"'";
              Statement smt1 = conn.createStatement();
            ResultSet rs1 = smt1.executeQuery(sql1);
            while (rs.next()) {
                FirstNameTF.setText(rs.getString("FirstName"));
                LastNameTF.setText(rs.getString("LastName"));
                MobilePersonalTF.setText(rs.getString("MobileNoPersonal"));
                MobileOfficeTF.setText(rs.getString("MobileNoOffice"));
                String dateValue = rs.getString("DOB");
                Date date = new SimpleDateFormat("yyyy-MM-dd").parse(dateValue);
                DOB.setDate(date);
                String gen = rs.getString("Gender");
                if (gen.equals("Male")) {
                    MaleBT.setSelected(true);
                } else {
                    FemaleBT.setSelected(true);
                }
                EmailTF.setText(rs.getString("Email"));
                EmailTF.setEditable(false);
                DesignationTF.setText(rs.getString("Designation"));
                DepartmentTF.setText(rs.getString("Department"));

                String dateValue1 = rs.getString("EmployeeJoiningDate");
                Date date1 = new SimpleDateFormat("yyyy-MM-dd").parse(dateValue1);
                JoiningDate.setDate(date1);
            
       
                
                VillageTF.setText(rs.getString("Village"));
                P_PostOfficeTF.setText(rs.getString("PostOffice"));
                District.setSelectedItem(rs.getString("District"));

            }
            while (rs1.next())
            {
            PasswordTF.setText(rs1.getString("Pass"));
            }

        } catch (Exception e) {
            System.out.println(e);

        }

    }//GEN-LAST:event_ButtonShowActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmployeeInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmployeeInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmployeeInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmployeeInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EmployeeInfo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonSave;
    private javax.swing.JButton ButtonShow;
    private javax.swing.JButton ButtonUpdate;
    private com.toedter.calendar.JDateChooser DOB;
    private javax.swing.JTextField DepartmentTF;
    private javax.swing.JTextField DesignationTF;
    private javax.swing.JComboBox<String> District;
    private javax.swing.JTextField EmailTF;
    private javax.swing.JRadioButton FemaleBT;
    private javax.swing.JTextField FirstNameTF;
    private com.toedter.calendar.JDateChooser JoiningDate;
    private javax.swing.JTextField LastNameTF;
    private com.toedter.calendar.JDateChooser LeavingDate;
    private javax.swing.JRadioButton MaleBT;
    private javax.swing.JTextField MobileOfficeTF;
    private javax.swing.JTextField MobilePersonalTF;
    private javax.swing.JTextField P_PostOfficeTF;
    private javax.swing.JTextField PasswordTF;
    private javax.swing.JTextField VillageTF;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField searchTF;
    // End of variables declaration//GEN-END:variables
}
