
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.concurrent.TimeUnit;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author USER
 */
public class salary_generated_time extends javax.swing.JFrame {
private int empID;
private String userN;
    /**
     * Creates new form salary_generated_time
     */
    public salary_generated_time() {
        initComponents();
    }
    
    public salary_generated_time(int empId,String userName)
    {
        initComponents();
        empID=empId;
        userN=userName;
        
      
    }
  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ButtonGetPayment = new javax.swing.JButton();
        Month = new javax.swing.JComboBox<>();
        Year = new javax.swing.JComboBox<>();
        ButtonBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ButtonGetPayment.setText("Get Payment");
        ButtonGetPayment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonGetPaymentActionPerformed(evt);
            }
        });

        Month.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jan", "Feb", "Mar", "April", "May", "June", "July", "August", "September", "October", "November", "December" }));
        Month.setToolTipText("");

        Year.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1998", "1999", "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019", "2020", "2021", "2022", "2023", "2024", "2025", "2026", "2027", "2028", "2029", "2030", "2031", "2032", "2033", "2034", "2035", "2036", "2037", "2038", "2039", "2040", "2041", "2042", "2043", "2044", "2045", "2046", "2047", "2048", "2049", "2050" }));

        ButtonBack.setText("Back");
        ButtonBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(Month, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(Year, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ButtonGetPayment)
                .addContainerGap(60, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ButtonBack)
                .addGap(34, 34, 34))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonGetPayment)
                    .addComponent(Month, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Year, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 124, Short.MAX_VALUE)
                .addComponent(ButtonBack)
                .addGap(35, 35, 35))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonGetPaymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonGetPaymentActionPerformed
        // TODO add your handling code here:
     String Month=this.Month.getSelectedItem().toString();
     String month="";
     if(Month.equals("Jan"))
     {
         month="01";
     }
     else if(Month.equals("Feb"))
     {
         month="02";
     }
     else if(Month.equals("Mar"))
     {
     month="03";
     }
     else if(Month.equals("April"))
     {
         month="04";
     }
     else if(Month.equals("May"))
     {
        month="05";
     }
     else if(Month.equals("June"))
     {
         month="06";
     }
     else if(Month.equals("July"))
     {
     month="07";
     }
     else if(Month.equals("August"))
     {
         month="08";
     }
     else if(Month.equals("September"))
     {
     month="09";
     }
     else if(Month.equals("October"))
     {
         month="10";
     }
     else if(Month.equals("November"))
     {
     month="11";
     }
     else if(Month.equals("December"))
     {
     month="12";
     }
     
      try {  
             Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");  
             Connection conn = DriverManager  
                     .getConnection(  
                             "jdbc:sqlserver://localhost:1433;databaseName=HumanResource_payroll;selectMethod=cursor",   "sa", "123456");  
               
             //select sum(WorkingHours) from Employee_Working_Hours where DateOfWork like '%04-06' and EmployeeId=1;
            String sql ="select sum(WorkingHours) from Employee_Working_Hours where DateOfWork like '"+Year.getSelectedItem().toString()+"-"+month+"-%' and EmployeeId='"+empID+"'";
              
             Statement smt = conn.createStatement();
             ResultSet rs = smt.executeQuery(sql);
              if(rs.next()){
              System.out.println(rs.getLong(1));
                
              long hours = (long) (((rs.getLong(1))/(1000*60*60))%24);
              
              if(hours>=240 || (hours>=220 && hours<240)|| hours<=0)
              {
                  new salaryGenerated(empID,hours,userN).setVisible(true);
                  
                  System.out.println(empID);
                  setVisible(false);
              }
              
              
              else{
              
              System.out.println("error");
                  JOptionPane.showMessageDialog(rootPane,"Can't Salary Generated for low time of work");
                  new EmployeeLoggedIn(userN,empID).setVisible(true);
                  setVisible(false);
              }
                
              }
      
      }catch(Exception e){
                 
             
             }
     
     
     
     
        
    }//GEN-LAST:event_ButtonGetPaymentActionPerformed

    private void ButtonBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonBackActionPerformed
        // TODO add your handling code here:
        new EmployeeLoggedIn(userN,empID).setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_ButtonBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(salary_generated_time.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(salary_generated_time.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(salary_generated_time.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(salary_generated_time.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new salary_generated_time().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonBack;
    private javax.swing.JButton ButtonGetPayment;
    private javax.swing.JComboBox<String> Month;
    private javax.swing.JComboBox<String> Year;
    // End of variables declaration//GEN-END:variables
}
